/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdicionarRouteImport } from './routes/adicionar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as CuponsIndexRouteImport } from './routes/cupons.index'
import { Route as ProdutosIdRouteImport } from './routes/produtos.$id'
import { Route as CuponsIdRouteImport } from './routes/cupons.$id'

const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarRoute = AdicionarRouteImport.update({
  id: '/adicionar',
  path: '/adicionar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsIndexRoute = CuponsIndexRouteImport.update({
  id: '/cupons/',
  path: '/cupons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIdRoute = ProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsIdRoute = CuponsIdRouteImport.update({
  id: '/cupons/$id',
  path: '/cupons/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/cupons/$id': typeof CuponsIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/cupons/': typeof CuponsIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/cupons/$id': typeof CuponsIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/cupons': typeof CuponsIndexRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/cupons/$id': typeof CuponsIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/cupons/': typeof CuponsIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar'
    | '/auth'
    | '/calendario'
    | '/cupons/$id'
    | '/produtos/$id'
    | '/cupons/'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar'
    | '/auth'
    | '/calendario'
    | '/cupons/$id'
    | '/produtos/$id'
    | '/cupons'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/adicionar'
    | '/auth'
    | '/calendario'
    | '/cupons/$id'
    | '/produtos/$id'
    | '/cupons/'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarRoute: typeof AdicionarRoute
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  CuponsIdRoute: typeof CuponsIdRoute
  ProdutosIdRoute: typeof ProdutosIdRoute
  CuponsIndexRoute: typeof CuponsIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar': {
      id: '/adicionar'
      path: '/adicionar'
      fullPath: '/adicionar'
      preLoaderRoute: typeof AdicionarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons/': {
      id: '/cupons/'
      path: '/cupons'
      fullPath: '/cupons/'
      preLoaderRoute: typeof CuponsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$id': {
      id: '/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof ProdutosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons/$id': {
      id: '/cupons/$id'
      path: '/cupons/$id'
      fullPath: '/cupons/$id'
      preLoaderRoute: typeof CuponsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarRoute: AdicionarRoute,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  CuponsIdRoute: CuponsIdRoute,
  ProdutosIdRoute: ProdutosIdRoute,
  CuponsIndexRoute: CuponsIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
